const strings = {
  splace:"Personal Finance Tracker",
  my_account:"My Account",
  personal_info:"PERSONAL INFO",
  profile:"Profile Pic",
  nick_name:"Nickname",
  account:"ACCOUNT",
  username:"Username",
  password:"Password",
  display_options:"DISPLAY OPTIONS",
  Currency:"Currency",
  Customize_Colors:"Customize Colors",
  showdid:"Show 'Did you know' on homepage",
  showPayment:"Show payment funds balance",
  showdebt:"Show debt balance",
  showtotal:"Show total debt balance",
  showcard:"Show notes in cards",
  reset:"Reset account",
  allUSer:"All user-entered data will be deleted, but your account",
  willRemain:"will remain active",
  delete:"Delete account",
  allData:"All data will be deleted permanently",
  hi_neelesh:"Hi Neelesh!1",
  planTrack:"Plan ,Track and achieve your payoff goal",
  primary:"Primary",
  deatFree:"DEBT-FREE COUNTDOWN",
  may:"MAY 2025",
  year:"years",
  months:"months",
  payOff:"Payoff progress",
  principle:"Principal paid",
  balance:"Balance",
  proMemberShip:"Pro Membership",
  multiDevice:"Multi-device access",
  adFree:"Ad-free",
  biWeekly:"Bi-weekly payments",
  unlimited:"Unlimited debts",
  manyMore:"Many more features",
  learnMore:"Learn more",
  planCelebrate:"Plan , Track, Celebrate",
  signUp:"Sign up",
  weSend:"We`ll send a verification code to your email.",
  email:"Email *",
  password1:"Password *",
  bySign:"By signing up you are agreeing to our",
  termOf:"Terms of Service",
  and:" and ",
  privatePolicy:"Privacy Policy",
  alreadySign:"Already signed up? ",
  signIn:"Sign in here",
  Use :"Use ",
  DPP1 :"DPP1 ",
  instead:"instead",
  FreeMember:"Free Member",
  termPolicy:"Term of Service | Privacy Policy",
  versinon:"Version 286104a6",
  skip:"Skip",
  next:"Next",
  debts:"Debts",
  manageAll:"Manage all your debts in one place",
  balanceBy:"Balance by category",
  add:"+ Add",
  DebtDetails:"Debt Details",
  Save:"Save",
  Advance:"Advance",
  X:" X",
  Category:"Category *",
  nick:"Nickname *",
  currentBalance:"Current balance *",
  annual:"Annual Percentage Rate *",
  minimum:"Minimum payment *",
  nextPayement:"Next payment due date *",
  an_otp:"An OTP has been sent to",
  Update_Profile:"Update Profile"  ,
  Sort_by:"Sort by",
  Balance:"Balance",
  Minimum:"Minimum",
  login:"Login",
};

export default strings;