const Icon = {
    splace: require("../assets/icons/flying_money.png"),
    left_arrow: require("../assets/icons/left_chevron.png"),
    logo: require("../assets/icons/Logo.png"),
    profile:require("../assets/icons/profile.png"),
    sun:require("../assets/icons/sunbg.png"),
    crown:require("../assets/icons/crown.png"),
    check:require("../assets/icons/check_mark.png"),
    home:require("../assets/icons/dove.png"),
    debts:require("../assets/icons/pie_chart.png"),
    plan:require("../assets/icons/clipboard.png"),
    strategy:require("../assets/icons/bulb.png"),
    track:require("../assets/icons/calendar.png"),
    right_arrow:require("../assets/icons/chevron.png"),
    king:require("../assets/icons/king.png"),
    briefcase:require("../assets/icons/briefcase.png"),
    video:require("../assets/icons/video.png"),
    logout:require("../assets/icons/logout.png"),
    question:require("../assets/icons/question.png"),
    search:require("../assets/icons/search.png"),
    arrow_down:require("../assets/icons/arrow_down.png"),
    percentage:require("../assets/icons/percentage.png"),
    inspiration:require("../assets/icons/inspiration.jpeg"),
    piggi:require("../assets/icons/piggybank.png"),
    student:require("../assets/icons/student.png"),
    mountain:require("../assets/icons/mountain.png"),
    hustle:require("../assets/icons/hustle.png"),
    calneder:require("../assets/icons/calendar.png"),
    google:require("../assets/icons/google.png"),
    apple:require("../assets/icons/apple.png"),
    edit:require("../assets/icons/edit.png")   
}

export default Icon;